baseURL = "http://example.org/"
title = "School Portal"
languageCode = "en-us"

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "JSON"]




