baseURL = "http://example.org/"
title = "School Portal"
languageCode = "en-us"

[taxonomies]
  teacher_tag = "teachers_tags"
  student_tag = "students_tags"


[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[outputs]
  home = ["HTML", "JSON"]




